version: '2.9'
services:
  pvdiary2:
    image: php:7-bullseye
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/containers/pvdiary2/data:/home
      - /data/containers/sbfspot/data:/home/pvdiary2/var/pvdiary/csv:ro
      - /data/containers/pvdiary2/scripts/entrypoint.sh:/bin/entrypoint.sh
    entrypoint: /bin/entrypoint.sh
    tmpfs:
      - /tmp
    environment:
      TIMEZONE: "Europe/Brussels"
    # Use environment variables in Portainer or in the shell to define RCLONE_HOST, RCLONE_USER & RCLONE_PASS
    # Delete the /home/pvdiary2/.config/rclone/rclone.conf file if you change these parameters to recreate the config
    # sync_params = "rclone://pvdiary:pvdiary"
      RCLONE_TYPE: "ftp"
      RCLONE_HOST: "${RCLONE_HOST}"
      RCLONE_USER: "${RCLONE_USER}"
      RCLONE_PASS: "${RCLONE_PASS}"
      RCLONE_EXPLICIT_TLS: "true"
      RCLONE_NO_CHECK_CERT: "true"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8082:8082"      
