FROM debian:latest
MAINTAINER:stan@gobien.be

# Install deps
RUN ["/bin/bash", "-c", "set -o pipefail \
  && DEBIAN_FRONTEND=noninteractive \
    apt update && apt install --assume-yes --no-install-recommends \
      build-essential \
      automake \
      vim \
      curl \
      wget \
      php-cli \
      php-readline \
      php-json \
      php-zip \
      php-sqlite3 \
      php-curl \
      tzdata \
      cron \
  && rm -rf /var/lib/apt/lists/* ]

# Time settings (hard coded for now)
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
RUN ["/bin/bash", "-c", "set -o pipefail \
  && PHPCONFPATH=$(php -i | grep "additional .ini files" |  grep -o '/[^ ]*') \
  && printf '[PHP]\ndate.timezone = "Europe/Brussels"\n' > $PHPCONFPATH/90-timezone.ini ]
  
# Create User
RUN adduser -d /home/pvdiary2 -U -m -p pvdiary2 pvdiary2


# Install PVdiary2

# Cronjobs
RUN printf '@reboot pvdiary2 /usr/local/bin/pvdiary --autorun --run --sleep=120 >> /var/log/cron.log 2>&1' > /etc/cron.d/pvdiary2
RUN printf '00 04 * * * pvdiary2 /usr/local/bin/pvdiary --autorun --run >> /var/log/cron.log 2>&1' >> /etc/cron.d/pvdiary2
RUN chmod 0644 /etc/cron.d/pvdiary2
RUN crontab /etc/cron.d/pvdiary2
RUN touch /var/log/cron.log

# Ports
EXPOSE 8081
 
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
