version: '2.9'
services:
  pvdiary2:
  # https://docs.portainer.io/v/ce-2.9/faq/troubleshooting/can-i-build-an-image-while-deploying-a-stack-application-from-git
  # Workaround for Portainer: Use the link to the build file in the portainer build image editor and name it pvdiary2:bullseye
  # Then deploy the stack succesfully
    build: https://raw.githubusercontent.com/Stan-Gobien/PVdiary2-Docker/main/PVdiary2/Dockerfile
    image: pvdiary2:bullseye
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/containers/pvdiary2/data:/home
      - /data/containers/sbfspot/data:/home/pvdiary2/var/pvdiary/csv:ro      
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "8082:8082"      
