version: '2.9'
services:
  pvdiary2:
  # https://docs.portainer.io/v/ce-2.9/faq/troubleshooting/can-i-build-an-image-while-deploying-a-stack-application-from-git
  # Workaround Use the link to the build file in the portainer build image editor and name it php-8-fpm-custom-ares:latest
  # Then deploy the stack succesfully
    build: https://raw.githubusercontent.com/Stan-Gobien/PVdiary2-Docker/main/PVdiary2/Dockerfile
    image: pvdiary2:bullseye
    restart: always
    mem_limit: 256m
    memswap_limit: 1024m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/containers/pvdiary2/data:/home
      - /data/containers/sbfspot/data/2021:/home/pvdiary2/var/pvdiary/csv/2021:ro
      - /data/containers/sbfspot/data/2022:/home/pvdiary2/var/pvdiary/csv/2022:ro
      - /data/containers/sbfspot/data/2023:/home/pvdiary2/var/pvdiary/csv/2023:ro
      - /data/containers/sbfspot/data/2024:/home/pvdiary2/var/pvdiary/csv/2024:ro
      - /data/containers/sbfspot/data/2025:/home/pvdiary2/var/pvdiary/csv/2025:ro
      - /data/containers/sbfspot/data/2026:/home/pvdiary2/var/pvdiary/csv/2026:ro
      - /data/containers/sbfspot/data/2027:/home/pvdiary2/var/pvdiary/csv/2027:ro
      - /data/containers/sbfspot/data/2028:/home/pvdiary2/var/pvdiary/csv/2028:ro
      - /data/containers/sbfspot/data/2029:/home/pvdiary2/var/pvdiary/csv/2029:ro
      - /data/containers/sbfspot/data/2030:/home/pvdiary2/var/pvdiary/csv/2030:ro
      - /data/containers/sbfspot/data/2031:/home/pvdiary2/var/pvdiary/csv/2031:ro
      
    tmpfs:
      - /tmp
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "8082:8082"      
